#!/usr/bin/python

"""Amulet tests on a basic cinder-backup deployment on precise-icehouse."""

from basic_deployment import CinderBackupBasicDeployment

if __name__ == '__main__':
    deployment = CinderBackupBasicDeployment(series='precise',
                                             openstack='cloud:precise-icehouse',
                                             source='cloud:precise-updates/icehouse')
    deployment.run_tests()
