#!/usr/bin/python

"""Amulet tests on a basic cinder-backup deployment on trusty-juno."""

from basic_deployment import CinderBackupBasicDeployment

if __name__ == '__main__':
    deployment = CinderBackupBasicDeployment(series='trusty',
                                             openstack='cloud:trusty-juno',
                                             source='cloud:trusty-updates/juno')
    deployment.run_tests()
