#!/usr/bin/python

"""Amulet tests on a basic cinder-backup deployment on trusty-kilo."""

from basic_deployment import CinderBackupBasicDeployment

if __name__ == '__main__':
    deployment = CinderBackupBasicDeployment(series='trusty',
                                             openstack='cloud:trusty-kilo',
                                             source='cloud:trusty-updates/kilo')
    deployment.run_tests()
