#!/usr/bin/python

"""Amulet tests on a basic cinder-backup deployment on vivid-kilo."""

from basic_deployment import CinderBackupBasicDeployment

if __name__ == '__main__':
    deployment = CinderBackupBasicDeployment(series='vivid')
    deployment.run_tests()
