#!/usr/bin/python

"""Amulet tests on a basic cinder-backup deployment on wily-liberty."""

from basic_deployment import CinderBackupBasicDeployment

if __name__ == '__main__':
    deployment = CinderBackupBasicDeployment(series='wily')
    deployment.run_tests()
