#!/usr/bin/python

"""Amulet tests on a basic cinder-backup deployment on xenial-mitaka."""

from basic_deployment import CinderBackupBasicDeployment

if __name__ == '__main__':
    deployment = CinderBackupBasicDeployment(series='xenial')
    deployment.run_tests()
